DROP TABLE IF EXISTS USERS, REQUESTS, ITEMS, BOOKINGS, COMMENTS;

CREATE TABLE USERS
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE REQUESTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT,
    requestor_id BIGINT REFERENCES USERS (id),
    CONSTRAINT pk_req PRIMARY KEY (id)
);

CREATE TABLE ITEMS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT REFERENCES USERS (id),
    request_id   BIGINT REFERENCES REQUESTS (id),
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE BOOKINGS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT REFERENCES ITEMS (id),
    booker_id  BIGINT REFERENCES USERS (id),
    status     VARCHAR(255),
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE COMMENTS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      TEXT                                    NOT NULL,
    item_id   BIGINT REFERENCES ITEMS (id),
    author_id BIGINT REFERENCES USERS (id),
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);